name: Social Readme

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: zylele/social-readme@master
        with:
          blog_rss_link: https://hsinyau.cc/feed
          blog_limit: 5 # blog数量
          douban_name: 179594693
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated douban # commit说明
